### ISSUE TITLE
ArduinoJson 5 in esp8266_artnet_dmx512.ino

### ISSUE THREAD

**Issue by Byonnem** [robertoostenveld/arduino#10]
Hi,

While compiling The artnet-DMX-512 project i got the following message

> esp8266_artnet_dmx512:206: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
> 
>      StaticJsonBuffer<300> jsonBuffer;
> 
>            ^
> 
> exit status 1
> StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

I solved this by downgrading ArduinoJson 6 to 5. However, i think it is desireable if a rewrite to A-JS 6 is made. 

With Kind Regards,

Menno

**Comment by robertoostenveld** [comment]
ArduinoJson 6 was for a long time flagged by the developer as "not ready for production use", because the interface to the functions was still changing. 

When I just checked the https://arduinojson.org website, it appears that version 6 is now considered stable. As such it would now be appropriate to convert the code from v5 to v6 according to https://arduinojson.org/v6/doc/upgrade/.

As it does not address a need that I have myself, I will not prioritize this. But I do welcome contributions in the form of a pull request.
