### ISSUE TITLE
Art-Net Neopixel Crash Reboot

### ISSUE THREAD

**Issue by sisensee** [robertoostenveld/arduino#3]
Art-Net Neopixel reboot. I am having an issue where the LED's will black out and you can see the chip is rebooting (goes yellow LED) then they come back on, around 5 seconds. Unfortunately where these are I cannot easily get to them nor connect a USB cable to monitor serial output. I will attempt that this next week. I was wondering if anyone else has had this issue. This happens at random intervals usually after several hours of being on.

**Comment by robertoostenveld** [comment]
I have had this issue myself (not with this hardware, but similar) when the power to the microprocessor would drop down a certain threshold. This can be either due to a digital-out pin drawing more current than the on-board voltage regulator can handle, or when the power supply itself is low, unstable, and spikes to a too-low voltage. In the latter case you may be able to solve it by adding a [electrolytic capacitor](https://www.sparkfun.com/products/96) between the supply voltage pin and ground. 

If it were the first case, it is a consequence of the attached LED strip. Fixing it is less trivial, but could be done with a transistor. I.e., the Wemos would switch the transistor on-off, which then switches the digital input to the LED strip on-off.

I recommend that you measure the supply voltage to see whether it is within specifications. Most informative is if you could do that with an oscilloscope; I got myself a [nano oscilloscope](https://www.seeedstudio.com/DSO-Quad-Aluminium-Alloy-Black-p-1034.html) for this type of diagnostics. But a multimeter might already show whether the voltages are on the low end, increasing the chance of a small downward spike in voltage causing a reboot.

**Comment by sisensee** [comment]
Previous installation was destroyed unable to verify solution. Closing issue
